#应用程序端口配置
server: 
  port: 20035
#  tomcat:
#    access-log-enabled: true

#日志配置    
logging: 
#    file: 
#    path: 
    config: classpath:logback.xml
#    level: 
#        org.springframework.web: ERROR
#        org.springframework.beans: ERROR


spring:
  profiles:
    active: ${spring.profiles.active}

---
# 开发环境配置
spring:
  profiles: dev

dubbo:
  registry:
    address: zookeeper://172.16.21.251:2181

---
# 测试环境配置
spring:
  profiles: test

dubbo:
  registry:
    address: zookeeper://172.19.23.94:2181

---
# 正式环境配置
spring:
  profiles: prd

dubbo:
  registry:
    address: zookeeper://172.19.204.172:2181